### ISSUE TITLE
the plugin isn't working properly

### ISSUE THREAD

**Issue by Dankfambo25** [xerpi/vita_udcd_uvc#3]
i have already installed the plugin via autoplugin and it's in 
(*KERNEL ur0:tai/udcd_uvc.skprx)
but no matter where i put the plugin at it's not running in the video applications like vlc or vita dock.
idk if this is an problem but i need help.

**Comment by xerpi** [comment]
Can you check if the device manager of your os shows the Vita?

**Comment by Dankfambo25** [comment]
it still says "ps vita" type b. What does it says when you have the plugin installed, also should i try ur0?

**Comment by Dankfambo25** [comment]
> This means my plugin isn't being loaded. Do you have a tai config in ux0?

yea i have an config.txt in ux0

**Comment by Dankfambo25** [comment]
ok so far what i have done is put your plugin in ur0 and it seems that instead of ps vita type b, it reads as ps vita. so in turn i also check my bluetooth and other devices which shows ps vita with an camera icon. now the big issue is that none of the applications like vitadock or obs isn't showing the vita. so at this point idk if it's my drivers or something.

**Comment by Dankfambo25** [comment]
> This means my plugin isn't being loaded. Do you have a tai config in ux0?

sorry for all of the replies i figure out what was the issue. it was multiple drivers on my ps vita that was interupting the vita itself from capturing on my pc.
